language: python
python:
- 3.6

sudo: false
env:
  global:
    secure: "HF6ymhIB9A3yo3ZbdyacdpeGUR0UOq5qTyH7D92GTYwPVLk0snxp0LypwD4OywUmcGD1wcxxvyUhncJRSDa6XM2AQLwKP97oFNadPdSje+gpI0lTvt5/iHBmxs9BvjXzZ6oVl8NJ/tL2vMCTsya/MrJVwJRIMPAr1fzrpcst6ClLziQHauAaNK"

install:
- pip install mkdocs mkdocs-material doctr

script:
- set -e 
- mkdocs build -d site
- doctr deploy . --built-docs site/