language: python
python: 3.7
jobs:
  include:
  - stage: test
    python: 3.6
  - python: 3.7
  - python: 3.8
  - script:
    - pytest --cov=pydrad --cov-report=html
    - coveralls
  - stage: docs
    script:
    - cd docs && make && cd ..
    - mkdocs build -d site
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GH_TOKEN"
      local_dir: site
      target_branch: gh-pages
stages:
- name: install
- name: test
- name: deploy
install:
- pip install -r requirements/requirements-dev.txt
- pip install --upgrade numpy>=1.16
- python setup.py install
script: pytest
env:
  global:
    - secure: "izAUaqDXefWLyOvg6uiMc/DaMtIdrB3SdAEHJaSM3kjk3JqsIXYtpxFEVIr5l7p90sSfFmUo4SUFO4IxewYVK9l9ipA02MryyPf7JHCes6zuuhmuB3T88E85TjJb2UQ+/OTeQN/P2X4EeBo4pmNzOjqgIq6hHF56Koxh1Ox7NsYWif64kjxaGbjvuTObctZfcIbSwtFpqBBF3Mw8Ok3F5etFU/vo1YDeKjBiNaOQVZnbrRQDL5Ll6q9ntAN8l9NZSrKSVV8dyAW/qp0LYB6Aqh9T6Ild/4OUgI97qnJRKqsdlCQt0N/aGhcs3nmT3ZR+kSTS5R9aUopMd+lHuMgPjLt/XLAYg9Z0YfLm/BZohIQRP/A9wLQh8Qt5d53ZYd5kQnxLazua8oz8QJwi9aWlhR86prqFl3qFjKfe398vGXYYsR/bHARIvVhMEtL8dWDImxlANlwgTQ7w8pUWo5XKdQ4PzT5+v4+Ke1ffOpBxnbYYLxJv2RY1jpW7Mu/suWTpVwJGHIXLyYqvFycignXeuKvW6TqS+HSuEYR8tOyowIrwWUukOtNIkj9wwL0iyJ1l2D/6EUWmBzzbuPC5ShRM7/hFUtsvDROHbiEaN4FMFyy2gWNmrLd8dhz52PZOriqhO2EL/y/P8eFzsJ/ytcvqxKurrwS5bEryq09fPHCWL4w="
