language: python
python: 3.7
jobs:
  include:
  - stage: test
    python: 3.6
  - python: 3.7
  - python: 3.8
  - script:
    - pytest --cov=pydrad --cov-report=html
    - coveralls
  - stage: docs
    script:
    - cd docs && make && cd ..
    - mkdocs build -d site
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      local_dir: site
      target_branch: gh-pages
stages:
- name: install
- name: test
- name: deploy
install:
- pip install -r requirements/requirements-dev.txt
- pip install --upgrade numpy>=1.16
- python setup.py install
script: pytest
env:
  global:
    secure: Seol4toIXfvZEa5IMUbaxcqQvkZi2Nr8ND4ysACLrHs6c01/L3mD8DUytfAofqpR97pJ39MJ5MT89HevV+NY4/R1x6sCOFEILxqtRE1ffNqtF6vhzmKjHhsFCoDFHELmKpjGkmnGIb52Ypl5VoOYtNO9CooNwvHnldU4aIx78MiET8IGZ3Ofz8g593hTRvNVAiYisXvWsfGfxLCW8ryATNfM0J057LiLJ7ZXeHKfb7dnbmWSOMXOlK2BGHegLUf+N88z8shnxojy1PaHTAgxnexx1K6Bmo9weWhLBPFCamhRCCAe0JyvWPZsgpmd7A1FnOJ22w9avkOWchE9nGuOxk+tCtdWuKVGuK0MYOIMgzjevnU3S1s75kYQQVI0Ep5IiudWwgZn4DY/ROpdBs6O8fTJldOZYpC7OG4LFhvvQX2OlZ7boNtPGBDM0yPTsvXYC7OuSHNBTqXVG58b4FfGGwU9AIi/QJAVARwDiNPvo9xZcnAh/MubNjmWIxaBsedDjH2QaivopqSGwSRVvZvKY8C3DdvEvFX4b9MLah0Uu71Plt31pfq3vZbDIY3qvQ/YRfRr2J6DJAKo0p2lPSoknN6ksjWIjnC3j1N5qwMrGIpSvYxJ0DWlgSix84gq3nWlakkZP3ll4e/n9oPft7vv6bRjF/5yEoADvCHt0PFzbms=
