language: python
python: 3.7
jobs:
  include:
  - stage: test
    python: 3.6
  - python: 3.7
  - python: 3.8
  - script:
    - pytest --cov=pydrad --cov-report=html
    - coveralls
  - stage: docs
    script:
    - cd docs && make && cd ..
    - mkdocs build -d site
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GH_TOKEN"
      local_dir: site
      target_branch: gh-pages
stages:
- name: install
- name: test
- name: deploy
install:
- pip install -r requirements/requirements-dev.txt
- pip install --upgrade numpy>=1.16
- python setup.py install
script: pytest
