language: c
os:
  - linux
sudo: false

jobs:
  include:
  - stage: test
    script:
    - pytest --cov=pydrad --cov-report=html
    - coveralls
  - script:
    - cd docs && make && cd ..
    - mkdocs build -d site
  - stage: deploy
    env: EVENT_TYPE='push cron'
    script:
    - cd docs && make && cd ..
    - set -e 
    - mkdocs build -d site
    - doctr deploy . --built-docs site/

stages:
- name: install
- name: test
- name: deploy

install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- python setup.py install

env:
  global:
    - PYTHON_VERSION=3.6
    - NUMPY_VERSION=stable
    - ASTROPY_VERSION=stable
    - PIP_DEPENDENCIES='plasmapy[theory] asdf mkdocs mkdocs-material doctr pydoc-markdown==2.0.2 pytest-cov coveralls'
    - CONDA_DEPENDENCIES='scipy matplotlib Jinja2 pytest'
    - EVENT_TYPE='pull_request push cron'
    - secure: "vC0YWMk1eIYqblncebSH1u7/+b65LSJehYPLiBBhr3FvYjf7Um1OD6kOOYR0fNRfPM4lQuAPLsdEckXwAN/vxOxiAARxdCv5SVRQlRO41wZGVIWcJMcRRDzdXa8eUFDB41nqADMJ8mt4eH/REcC4JTnuSloiI0TSPYIKM/KrOurW7x4HX7wNkEIURdAxFNICsiiIijGKSD5CyaiXGDrHVwlo9Q5UpKkaB/ltdR1sZ36K32W/QmUDgtYN99ZRxSS/HFC3o1eileNzL+dYlyLcYNeHuI2c1wPkRvLiPLgFz2k+hMRPcAxZ3PU2XYK1o6Ts+5w87Of/43d/JS4I9cOdO21ZlXbA6Q1o1vtPzB4OijVafymHlHrtHPjrtlLceHpbriE5iLoBeWxb6RTeMKlLDFi6qrcOCIVrke4+BmN+LQAzaLZAIfyaYc8LjNvQ0XyCXJ4LPMDpAEVRFDe+ahbQ8hPoWRyin7qV391m+iCavjtdkaxz1Ur42MaLimHpCehxzRHO8UgOZiHVQe2TJPqu9mdRqLuX72hxi0oiXFZyI53mHOZFaBDmZdwdMox8xA/Zpr6Z4YMvWVFXUz2Q/USSgiM0o7vDbMkb1nlMmkRxsCnxiLzMFY7X8lwR+QyS6fSqdo9OOGmqgOk4F+FRxiZHybsXhHVuINBpdrrrFj5x93Q="

