name: hydrad_tools
channels:
- defaults
dependencies:
- python
- pip
- numpy
- scipy
- matplotlib
- astropy
- Jinja2
- pip:
  - asdf
  - git+git://github.com/plasmapy/plasmapy.git  # dont use master once a new release is pushed
  