# Site Info
site_name: pydrad
site_description: Tools for running and parsing HYDRAD simulations
site_author: Will Barnes
site_url: 'https://rice-solar-physics.github.io/pydrad'

# Repository
repo_name: rice-solar-physics/pydrad
repo_url: https://github.com/rice-solar-physics/pydrad

# Navigation
nav:
- Getting Started: index.md
- Configuring a Simulation: configure.md
- Parsing the Results: parse.md
- Plotting: plot.md
- API:
  - pydrad.configure: api/configure.md
  - pydrad.parse: api/parse.md
  - pydrad.visualize: api/visualize.md

# Appearance
theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'yellow'
  icon:
    logo: 'fontawesome/solid/wrench'

# Extensions
markdown_extensions:
  - codehilite
  - pymdownx.arithmatex

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Social/Contact
extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'http://solar.rice.edu/'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/rice-solar-physics'
